/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch Surface & Neutral System
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#565e74',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        background: '#f8f9ff',
        'on-background': '#0b1c30',

        // Primary (Black / High-contrast Slate)
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#7c839b',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-primary': '#bec6e0',

        // Secondary & Brand Green (Emerald / Campus Forest)
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',

        // Brand Palette explicit tokens
        brand: {
          emerald: '#059669',
          'emerald-hover': '#047857',
          'emerald-subtle': '#ECFDF5',
          navy: '#0F172A',
          'navy-light': '#1E293B',
        },

        // Tertiary
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00174b',
        'on-tertiary-container': '#497cff',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed': '#00174b',
        'on-tertiary-fixed-variant': '#003ea8',

        // Error & Status Colors
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        status: {
          success: '#10B981',
          'success-bg': '#ECFDF5',
          warning: '#D97706',
          'warning-bg': '#FFFBEB',
          info: '#2563EB',
          'info-bg': '#EFF6FF',
          danger: '#DC2626',
          'danger-bg': '#FEF2F2',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-hero-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'price-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'price-md': ['17px', { lineHeight: '22px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
      spacing: {
        gutter: '1rem',
        'gutter-md': '1.25rem',
        'gutter-lg': '1.5rem',
        margin: '1rem',
        'margin-md': '2rem',
        'margin-lg': '3rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        level1: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        level2: '0 4px 6px -1px rgba(15, 23, 42, 0.07), 0 2px 4px -2px rgba(15, 23, 42, 0.05)',
        level3: '0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.04)',
        level4: '0 20px 25px -5px rgba(15, 23, 42, 0.12), 0 8px 10px -6px rgba(15, 23, 42, 0.06)',
      },
    },
  },
  plugins: [],
};
